### ISSUE TITLE
Code review - by Charles Webb

### ISSUE THREAD

**Issue by CharlesWbb** [oliviadxvey/CMP1903-A01#8]
Code Review 
Charles Webb (25757569)

Olivia, 

I've had the chance to review your code and I must say that I'm impressed with how readable it is. Your naming conventions are consistent throughout the code, making it easy to follow. However I have found a number of issues that you may want to correct.

The first issue I came across with your code, was not handling erroneous input properly. This code snippet is what caused said issue: 

programType = Console.ReadLine(); 

            if (programType != "T" && programType != "F") { 

                throw new FormatException("Value must be single character, either T or F."); 

            } 

 
If I enter a lower case t or f. The program crashes. This will probably lower your grade. You'll still pass but you'd be unlikely to achieve 1st honours. You may want to try using the built in string functions in c#. One function you can use is .ToUpper() which will convert users input into uppercase, preventing the crash.  

Carrying on from my first point. While the code throws exceptions. It should also tell the user what they are doing wrong, and how they should be interacting with your code properly. This would increase program usability and prevent frustration and confusion while using your program.  
 
Your code does detect errors, but the code still crashes when an error occurs. This isn’t best practice. Personally I contain code that obtains user data in a loop(while using try catches), and the loop only ends when the user inputs correct information. This prevents the code from crashing, and ensures correct information is entered.  

Your program.cs class is lacking comments. In other classes you frequently use comments. But in the you only state what the code does, which is fine, but you could also explain why you are doing something in that particular way, or how the code works. 

The next time you develop a program, would you consider improving the useability of it? For example, instead of outputting "Your card: 6 of 1"(which may confuse some people), try "your card is the 6 of aces". This would increase the useability of you program(as it is easier to use) at the cost of spending more time developing the program, do you think it would be worth the trade-off? Thirdly, do you think that due to the errors present in your code, that more time or different testing should have been made?. For example, a form unit testing would be easy to use with c#'s oop paradigm and would make it a lot easier to find and also correct bugs.
 

Things I do like about your code is its readability. The code was understandable and clear, I would consider it to be self-commenting code. Your naming of variables is also very good and consistent throughout.  

I hope you find my review useful,

Keep up the excellent work, 
-Charles

**Comment by oliviadxvey** [comment]
Thank you Charles for your helpful comments, I have already begun working on making the changes.

**Comment by CharlesWbb** [comment]
Are you sure you need to make changes? I don’t think you do. But don’t take
my word for it
